blank_issues_enabled: true
contact_links:
  - name: Feature Request
    url: https://github.com/linkb15/cms/discussions/categories/ideas
    about: Suggest an idea to improve Linkbcms in our GitHub Discussions
  - name: Question about Linkbcms
    url: https://github.com/linkb15/cms/discussions/categories/q-a
    about: Please ask Linkbcms-related questions in our GitHub Discussions
